### ISSUE TITLE
Java - log shows error messages

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-hcs-sxc-java#385]
**Actual Behavior**
Error messages (see below) appear in the logs

**Expected Behavior**
No error messages 

```
Alice    | javax.crypto.AEADBadTagException: Tag mismatch!
Alice    | 	at java.base/com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:623)
Alice    | 	at java.base/com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1116)
Alice    | 	at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1053)
Alice    | 	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
Alice    | 	at java.base/com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:446)
Alice    | 	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
Alice    | 	at com.hedera.hcs.sxc.plugin.cryptography.cryptography.Cryptography.decrypt(Cryptography.java:121)
Alice    | 	at com.hedera.hcs.sxc.callback.OnHCSMessageCallback.partialMessage(OnHCSMessageCallback.java:166)
Alice    | 	at com.hedera.hcs.sxc.plugin.mirror.subscribe.MirrorTopicSubscriber.onMirrorMessage(MirrorTopicSubscriber.java:126)
Alice    | 	at com.hedera.hcs.sxc.plugin.mirror.subscribe.MirrorTopicSubscriber.lambda$subscribe$0(MirrorTopicSubscriber.java:91)
Alice    | 	at com.hedera.hashgraph.sdk.mirror.MirrorConsensusTopicQuery$1.onNext(MirrorConsensusTopicQuery.java:60)
Alice    | 	at com.hedera.hashgraph.sdk.mirror.MirrorConsensusTopicQuery$1.onNext(MirrorConsensusTopicQuery.java:57)
Alice    | 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:436)
Alice    | 	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
Alice    | 	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
Alice    | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:599)
Alice    | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:584)
Alice    | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
Alice    | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
Alice    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Alice    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Alice    | 	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gregscullard** [comment]
Rotation was enabled (and not yet fully implemented), not an issue.

**Comment by architarai21** [comment]
How was this issue resolved?
