### ISSUE TITLE
Java - logs show wire type exceptions

### ISSUE THREAD

**Issue by gregscullard** [hashgraph/hedera-hcs-sxc-java#386]
**Actual Behavior**
Errors (see below) appear in the logs

**Expected Behavior**
No errors in logs

```
Bob      | 15:50:23.542 [grpc-default-executor-1] INFO  c.h.h.s.p.m.s.MirrorTopicSubscriber - Got message from mirror - calling back
Bob      | 15:50:23.712 [grpc-default-executor-1] ERROR c.h.h.integration.HCSIntegration - com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
Bob      | com.google.protobuf.InvalidProtocolBufferException$InvalidWireTypeException: Protocol message tag had invalid wire type.
Bob      | 	at com.google.protobuf.InvalidProtocolBufferException.invalidWireType(InvalidProtocolBufferException.java:111)
Bob      | 	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:557)
Bob      | 	at com.google.protobuf.GeneratedMessageV3.parseUnknownField(GeneratedMessageV3.java:320)
Bob      | 	at proto.SettlementBPM.<init>(SettlementBPM.java:309)
Bob      | 	at proto.SettlementBPM.<init>(SettlementBPM.java:16)
Bob      | 	at proto.SettlementBPM$1.parsePartialFrom(SettlementBPM.java:4262)
Bob      | 	at proto.SettlementBPM$1.parsePartialFrom(SettlementBPM.java:4256)
Bob      | 	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:158)
Bob      | 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:191)
Bob      | 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:203)
Bob      | 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:208)
Bob      | 	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
Bob      | 	at proto.SettlementBPM.parseFrom(SettlementBPM.java:1309)
Bob      | 	at com.hedera.hcsapp.integration.HCSIntegration.processHCSMessage(HCSIntegration.java:98)
Bob      | 	at com.hedera.hcsapp.integration.HCSIntegration.lambda$new$0(HCSIntegration.java:91)
Bob      | 	at com.hedera.hcs.sxc.callback.OnHCSMessageCallback.lambda$notifyObservers$0(OnHCSMessageCallback.java:139)
Bob      | 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
Bob      | 	at com.hedera.hcs.sxc.callback.OnHCSMessageCallback.notifyObservers(OnHCSMessageCallback.java:139)
Bob      | 	at com.hedera.hcs.sxc.callback.OnHCSMessageCallback.partialMessage(OnHCSMessageCallback.java:295)
Bob      | 	at com.hedera.hcs.sxc.plugin.mirror.subscribe.MirrorTopicSubscriber.onMirrorMessage(MirrorTopicSubscriber.java:126)
Bob      | 	at com.hedera.hcs.sxc.plugin.mirror.subscribe.MirrorTopicSubscriber.lambda$subscribe$0(MirrorTopicSubscriber.java:91)
Bob      | 	at com.hedera.hashgraph.sdk.mirror.MirrorConsensusTopicQuery$1.onNext(MirrorConsensusTopicQuery.java:60)
Bob      | 	at com.hedera.hashgraph.sdk.mirror.MirrorConsensusTopicQuery$1.onNext(MirrorConsensusTopicQuery.java:57)
Bob      | 	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onMessage(ClientCalls.java:436)
Bob      | 	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
Bob      | 	at io.grpc.ForwardingClientCallListener.onMessage(ForwardingClientCallListener.java:33)
Bob      | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInternal(ClientCallImpl.java:599)
Bob      | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1MessagesAvailable.runInContext(ClientCallImpl.java:584)
Bob      | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
Bob      | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
Bob      | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
Bob      | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
Bob      | 	at java.base/java.lang.Thread.run(Thread.java:834)
Bob      | 15:50:23.712 [grpc-default-executor-1] INFO  c.h.h.s.p.m.s.MirrorTopicSubscriber - Got message from mirror - ackn
```

**Comment by zoperado** [comment]
This one is related to encryption being on when it shouldn't
